### Environment specific non secure  properties go here ###


### API ID ### Create API Configuration in API Manager for DEV Env and update the id. 
api:
  id: "18650004"
  

https:
  listener:
    host: "0.0.0.0"
  private:   
    port: "8092"
json:
  logger:
    disabled:
      fields: ""

http:
  fico:
    host: "bnb-it-fico-sapi-v1.us-e2.cloudhub.io"
    port: ""
    baseUri: "/api/v2"
    ordersPath: "/orders"
    ordersByIdPath: "/orders/{id}"
    searchBusinessPath: "/search-business"
    clientId: "${secure::mulesoft.client_id}"
    client_secret: "${secure::mulesoft.client_secret}"
    